#Theme Name: Handsomely
#CMS - Jekyll
#Developer- Deenesh Chowdhary
#http://deeneshchowdhary.com
title: "Stained Glass Zealot"
site-description: "Revival of beauty"
email: stainedglasszealot@gmail.com
description: "Revive beauty"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://glasszealot.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
email_username: stainedglasszealot@gmail.com #Your email address
twitter_username: glass_zealot #Twitter Username goes here
insta_username: glass_zealot #Twitter Username goes here
your_name: Stained Glass Zealot Blog #Your Name for About
about_yourself: "Duis interdum tincidunt risus. Integer a pellentesque nulla, ut tempus nunc. Mauris sed tortor vitae leo ullamcorper suscipit. Donec dignissim sollicitudin rutrum. Nam eleifend fermentum neque, a dictum velit. Nullam malesuada, nulla a dapibus efficitur, metus tortor sodales dui, eu luctus urna eros nec ipsum. Suspendisse id neque tristique, efficitur orci ut, blandit libero. Curabitur pellentesque condimentum ipsum, sed fermentum diam dictum ac. Curabitur eu aliquam neque, eu vulputate ipsum. Aliquam erat volutpat. " # Brief description about yourself
copyright_name: GlassZealot #Copyright
# Build settings
markdown: kramdown
paginate: 5 #Total Number of Post in each Page
gems: [jekyll-paginate, jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
